src/Entity/Vat/FixedVat.php
<?php

namespace App\Entity\Vat;

class FixedVat implements VatInterface
{
    /** @var float */
    protected $rate;

    /**
     * @param float $price
     */
    public function __construct(float $price)
    {
        $this->rate = $price;
    }

    public function getVatRate(): float
    {
        return $this->rate;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\DataProvider\OrderDao;
use App\DataProvider\PromotionDao;
use App\Exception\PromotionValidationRuleException;
use App\Service\Price\Calculator;
use App\Validator\PromotionRulesValidator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(
        OrderDao $orderDao,
        PromotionDao $promotionDao,
        PromotionRulesValidator $promotionRulesValidator,
        Calculator $priceCalculator,
        \App\Service\ShippingFee\Calculator $shippingFeeCalculator
    ): Response
    {
        $order = $orderDao->getCurrentOrder();
        //$order = $orderDao->getOtherOrder();

        // Simulation : l'utilisateur entre un code promo existant
        $promotion = $promotionDao->getPromotionByName();
        $order->setPromotion($promotion);

        // Validation de la promotion
        $promotionValidatorError = null;
        try {
            $promotionRulesValidator->validatePromotion($order);
        } catch(PromotionValidationRuleException $e) {
            $promotionValidatorError = $e->getMessage();
        }


        return $this->render('cart/details.html.twig', [
            'title' => 'Votre panier : ' . count($order->getItems()) . ' produit(s)',
            'order' => $order,
            'priceCalculator' => $priceCalculator,
            'shippingFeeCalculator' => $shippingFeeCalculator,
            'promotionValidatorError' => $promotionValidatorError
        ]);
    }

    /**
     * @Route("/payment", name="payment")
     */
    public function payment() {
        return new Response('Offert par la maison :D');
    }
}

templates/cart/details.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <div class="row">
        {% for item in order.items %}
            <div class="col-sm-1 col-md-3 col-lg-4 p-2">
                <div class="card cart-item">
                    <img src="{{ asset('build/thumbnail.jpg') }}" class="card-img-top" alt="{{ item.product.title }}">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ item.product.title }}
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">
                            {{ item.product.brand.name }}
                        </h6>
                        <p class="card-text">
                            <table class="table table-sm">
                                <tbody>
                                    <tr>
                                        <th scope="row">Quantité</th>
                                        <td>{{ item.quantity }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Prix unitaire</th>
                                        <td>{{ item.product.price|format_currency('EUR') }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Sous-Total HT</th>
                                        <td>{{ priceCalculator.getItemVatFreeTotalPrice(item)|format_currency('EUR') }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">TVA</th>
                                        <td>{{ item.product.brand.vat.vatRate }}%</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Total TTC</th>
                                        <td>{{ priceCalculator.getItemTotalPrice(item, order.billingCountry)|format_currency('EUR') }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </p>
                        <a href="{{ path('product', {id: 1}) }}" class="btn btn-primary">Consulter</a>
                        <a href="#" class="btn btn-danger">Retirer</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="offset-5 col-7 p-2">
            <div class="card cart-resume">
                <div class="card-body">
                    <h5 class="card-title">
                        Résumé
                    </h5>
                    <p class="card-text">
                        <table class="table table-sm">
                            <tbody>
                                <tr>
                                    <th scope="row">Sous-Total HT</th>
                                    <td>{{ priceCalculator.vatFreeSubtotalPrice(order)|format_currency('EUR') }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Frais de port HT</th>
                                    <td>{{ shippingFeeCalculator.shippingFeeTotalPrice(order)|format_currency('EUR') }}</td>
                                </tr>
                                {% if order.promotion != null %}
                                    <tr>
                                        <th scope="row">Promotion</th>
                                        <td>
                                            <span class="{{ promotionValidatorError != null ? 'text-danger text-strike' }}">{{ order.promotion.name }} -{{ order.promotion.reduction }}%</span>
                                            {% if promotionValidatorError != null  %}<p class="text-danger">{{ promotionValidatorError }}</p>{% endif %}
                                        </td>
                                    </tr>
                                {% endif %}
                                <tr>
                                    <th scope="row">Total HT</th>
                                    <td>{{ priceCalculator.vatFreeTotalPrice(order)|format_currency('EUR') }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Total TTC</th>
                                    <td>{{ priceCalculator.totalPrice(order)|format_currency('EUR') }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </p>
                    <a href="{{ path('payment') }}" class="btn btn-success float-end">Accèder au paiement</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}